Merge v4 to main
quartznet/quartznet pull request #1568
Opened 2022-03-27 11:32 UTC by lahma

I've rebased the current v4 and minor cleanup. @drieseng @jafin now is a good time to check out the commit history and yell STOOOP if you find something concerning. I can rewrite messages and commits if needed, when I get green light I can merge to main. I've branched 3.x for maintenance now.

2022-03-27 13:00 UTC, jafin requested changes
Looked over the content I'm familiar with LGTM,  a few duplicate TargetFramework attributes to remove is all I see to correct.

2022-03-27 13:00 UTC, jafin commented on src/Quartz.Jobs/Quartz.Jobs.csproj
>      <TargetFrameworks>net462;net472;netstandard2.0</TargetFrameworks>
Duplicate line to remove.

2022-03-27 13:00 UTC, jafin commented on src/Quartz.Plugins.TimeZoneConverter/Quartz.Plugins.TimeZoneConverter.csproj
>      <TargetFrameworks>net462;net472;netstandard2.0</TargetFrameworks>
Duplicate TargetFramework line to remove.

2022-03-27 13:01 UTC, jafin commented on src/Quartz.Examples/Quartz.Examples.csproj
>      <TargetFrameworks>net6.0;net462</TargetFrameworks>
Duplicate TargetFramework line remove.

2022-03-27 13:02 UTC, jafin commented on src/Quartz.Plugins/Quartz.Plugins.csproj
>      <TargetFrameworks>net462;net472;netstandard2.0</TargetFrameworks>
Duplciate TargetFrameworks remove.

2022-03-27 13:02 UTC, jafin commented on src/Quartz.Serialization.Json/Quartz.Serialization.Json.csproj
>      <TargetFrameworks>net462;net472;netstandard2.0</TargetFrameworks>
Duplicate targetFrameworks line remove.

2022-03-27 13:02 UTC, jafin commented on src/Quartz.Server/Quartz.Server.csproj
>      <TargetFrameworks>net462;net6.0</TargetFrameworks>
Duplicate targetFrameworks line remove.

2022-03-27 13:03 UTC, jafin commented on src/Quartz/Quartz.csproj
>      <TargetFrameworks>net462;net472;netstandard2.0</TargetFrameworks>
Duplicate targetFrameworks lines remove.

2022-03-27 14:30 UTC, lahma commented
@jafin thanks for the review! Good catch, git csproj merge strikes once again - I think I've fixed them in force-pushed top commit.

2022-03-27 22:14 UTC, jafin approved these changes

2022-03-29 16:51 UTC, lahma commented
OK it seems that to get a first bug report from 3.4 release we need to merge this into main - that's just Mr. Murphy's law. There's automation to allow releases from 3.x branch too so I'm not that worried.

2022-03-29 16:52 UTC, merged