Serialized field for Job Type to enable maintenance on Jobs that cannot be constructed to their Type
quartznet/quartznet pull request #1610
Opened 2022-05-21 06:37 UTC by jafin

Reduce the need to construct the stored job `Type` , allowing maintenance tasks such as `UnschduleJob` to operate when the stored job Type can no longer be constructed.
JobTypeSerialized is stored and can be retrieved as Type still via a Lazy getter

It should be a `Non-breaking change`, but if external code depended on exceptions being thrown for invalid job type retrieval this might introduce unexpected results

Should resolve #1560  - (V4) Error in JobDetailImpl due to null JobType being passed

2022-05-21 06:38 UTC, jafin commented
For review, if there are better names to use than StorableTypeName etc let me know.

2022-05-21 06:58 UTC, lahma requested changes
Great initiative! I think we can break things with v4 so I don't see why we would need to have two competing concepts (Type and JobType), everything should be JobType.

2022-05-21 06:58 UTC, lahma commented on src/Quartz.Tests.Integration/JobMaintenanceTests.cs
> +[TestFixture]
nit: no need for TestFixture

2022-05-21 06:58 UTC, lahma commented on src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj
> +  <ItemGroup>
looks unnecessary

2022-05-21 06:58 UTC, lahma commented on src/Quartz/IJobDetail.cs
> +        /// <summary>
I think we should just break the API and change `JobType` to be of type `JobType`, maybe even change the property name to `Type`?

2022-05-21 06:58 UTC, lahma commented on src/Quartz/Impl/JobType.cs
> +public class JobType
this should be sealed, I think also allowing implicit conversion for `Type` might be a good thing?

2022-05-21 06:58 UTC, lahma commented on src/Quartz/Impl/JobType.cs
> +    public JobType()
Probably doesn't make sense to allow without parameter, should be private

2022-05-21 06:58 UTC, lahma commented on src/Quartz/Impl/JobType.cs
> +    public JobType(string? typeStorageName)
I think the logical name would be `typeName`, like it's named in `Type.GetType`?

2022-05-21 06:58 UTC, lahma commented on src/Quartz/Impl/JobType.cs
> +    public string StorableTypeName
I think this is just `Name`, or `FullName`, should follow same sort of naming logic in `Type`

2022-05-21 06:58 UTC, lahma commented on src/Quartz/JobBuilder.cs
> +                                     new JobType(jobTypeSerialized),
implicit conversion operator between Type and and JobType should make this redundant

2022-05-21 06:58 UTC, lahma commented on src/Quartz/JobBuilder.cs
> +        public JobBuilder WithJobTypeSerialized(string? jobTypeSerialized)
this should probably be `OfType(string typeName)` to use same naming and overloads as passing Type, JobType and Type should be interchangeable concepts

2022-05-22 00:09 UTC, jafin commented
@lahma thanks I'll update based on your feedback.

Are you ok with `JobDetailImpl()` constructor being removed?  The only usage in the library is via 2 tests, which can be corrected. 
I can't see a reason to construct this without specifying a name/category and Type (which is done via the other constructors)
It will avoid making JobType property nullable is all.

2022-05-22 17:54 UTC, lahma commented
Removing constructor allowing invalid state should be fine. Only thing that springs to my mind is whether this can break serialization? Like full framework remoting probably allows to pass job impls.

2022-05-29 00:07 UTC, jafin commented
@lahma  I've updated code with suggested changes for review.

I noted a request in #1523 to allow the creation of a JobType remotely, where the type is not known to the remote code. This should enable this.

### Remoting Serialization
Tests exist in `JobDetailTest -> JobDetailsShouldBeSerializable` to validate remoting serialization.

> Constructors are not called when objects are deserialized.
[src](https://docs.microsoft.com/en-us/dotnet/standard/serialization/serialization-guidelines)

### Breaking changes

- JobType parameterless constructor removed, construct with either `Type FullName` or Job `Type` now.

2022-05-29 08:03 UTC, lahma approved these changes

2022-05-29 08:04 UTC, lahma commented
Great work and looks good, I did couple small tweaks I didn't want to bother you with and slow down the process of getting into main.

2022-05-29 08:10 UTC, merged

2022-05-29 08:10 UTC, drieseng requested changes

2022-05-29 08:10 UTC, drieseng commented on src/Quartz/Impl/JobType.cs
> +    private Lazy<Type> type = new(() => throw new InvalidOperationException("Type not defined"));
Do we want to pay this extra cost for creating a job type:

|        Method |        Mean |     Error |    StdDev |      Median |  Gen 0 | Allocated |
|-------------- |------------:|----------:|----------:|------------:|-------:|----------:|
| Type |  16.9039 ns | 0.1538 ns | 0.1364 ns |  16.8752 ns | 0.0057 |      24 B |
| JobType | 162.0058 ns | 2.1970 ns | 1.9476 ns | 161.9113 ns | 0.1185 |     497 B |

Once initialized the extra cost is negligable:

|        Method |        Mean |     Error |    StdDev |      Median |  Gen 0 | Allocated |
|-------------- |------------:|----------:|----------:|------------:|-------:|----------:|
|      Type |   0.0031 ns | 0.0120 ns | 0.0106 ns |   0.0000 ns |      - |         - |
|      JobType |   4.1255 ns | 0.1113 ns | 0.2646 ns |   4.0576 ns |      - |         - |

Use of **Lazy\<T>** should also have impact on concurrency. Haven't had time to benchmark this.

2022-05-29 08:10 UTC, drieseng commented on src/Quartz/Impl/JobType.cs
> +    public static implicit operator Type(JobType jobType) => jobType.Type;
I don't like implicit conversions ...

2022-05-29 08:11 UTC, drieseng commented
@lahma I was too slow, it seems ....

2022-05-29 08:25 UTC, drieseng commented
@lahma The way I see it, we only have a single use case for building a **IJobDetail** without a concrete job type: remove a trigger for a job type that cannot be resolved.

Why not introduce another method that can be used by `JobStoreSupport.RemoveTrigger(...)` that does not return an *IJobDetail**, but only a **JobKey** (or a tuple representing the **JobKey** and its **durable** characteristic)?

2022-05-29 08:31 UTC, lahma commented
Retrieve list of job details to a process which does not have job type library. That's the main use case.

2022-05-29 08:39 UTC, drieseng commented
Can you have a look at my remarks. I think most of them remain valid.

2022-05-29 08:43 UTC, lahma commented
I'll have a closer look when I find the time, thanks for doing the review.

2022-05-29 10:31 UTC, jafin commented
Hi @drieseng / @lahma ,  Thanks for the continued review.
Just to note all points raised:

> @lahma The way I see it, we only have a single use case for building a IJobDetail without a concrete job type: remove a trigger for a job type that cannot be resolved.

@drieseng There is another use case presented in #1523 , ability to create jobs remotely without having access to the Type.  This sounds like a valid use case.

> I don't like implicit conversions ...

I added this at the request of @lahma ,  I don't have a strong opinion on this, I think it makes it easier for the consumer, but uncertain what you both agree on.

> Do we want to pay this extra cost for creating a job type:

I can't answer that, I was implementing a feature fix, not directly focused on performance.  If there is a better/faster way while still achieving the intent of the change, please advise.  
I see that [Lazy<T> performance is attributed to Activator.CreateInstance](https://stackoverflow.com/questions/11236855/is-using-lazyt-bad-for-performance)

Would removing the Lazy<T> and constructing the Type once on first get, then storing in a backing field be more appropriate?


> public string FullName
> Please remove default, and always assign in actors.

Yes, I'll fix that.

> public JobType(string? fullName)
> Should not be nullable (since it is in fact not allowed to be null).

Yes will fix.

I'll do another fixup PR with the issues above.  Leaving out changes on implicit conversions, and await further advice on performance implications for now.

2022-05-29 21:08 UTC, drieseng commented
@jafin Let me have a look at what we can do for performance, if necessary. The cost of creating an **IJobDetail* is not that important.

A few options to consider to reduce the cost of **JobType**:
** Allow **JobType** to have a reference to both a type or a full name.  If constructed using a **Type**, have **JobType.FullName** just return the **FullName** of the **Type** (or the assembly qualified name without version, more on this below) and have **Type** return the **Type** instance that was used to construct the **JobType**.
When constructed using an assembly qualfified name (without version) have, then lazily create the **Type** when the **JobType.Type** is accessed. This can be done with or without **Lazy\<T>**, to be investigated.
* Redefine **JobType** as struct instead of a reference type. Not too sure I like this.

I gave it a little more though, and really think we were too fast in merging this PR.
On the surface it gives you the impression that nothing changed (eg. by having an implicit conversion to **Type**), and it's that what makes me uneasy with it.

For example, we have the following code in **QuartzDiagnostic** that is "broken" by this PR:
```cs
.WithTag(DiagnosticHeaders.JobType, jobContext.JobDetail.JobType.ToString())
```

Same for someone that currently uses **IJobDetail.JobType.FullName**.  I'm sure they do not expect the result to be the assembly qualified name (without version).

Of course it's ok to introduce breaking changes in v4. But with this PR we're introducing breaking changes while - at the same time - we try (and somehow fail) to hide these breaking changes.

As always, it's far easier to identify what is "wrong" than to come up with a solution. I'll give this some thought and try to give more constructive feedback later.

2022-05-29 21:37 UTC, lahma commented
> I gave it a little more though, and really think we were too fast in merging this PR.
> On the surface it gives you the impression that nothing changed (eg. by having an implicit conversion to **Type**), and it's that what makes me uneasy with it.
> 
> For example, we have the following code in **QuartzDiagnostic** that is "broken" by this PR:
> ```cs
> .WithTag(DiagnosticHeaders.JobType, jobContext.JobDetail.JobType.ToString())
> ```

That's a good example where version should not matter. Assembly qualified name without version is correct. This PR was very important progress to remedy a long-standing issue.

> Of course it's ok to introduce breaking changes in v4. But with this PR we're introducing breaking changes while - at the same time - we try (and somehow fail) to hide these breaking changes.

V3 was about keeping Java version resemblance, but as there has been very little progress on that front, probably a lost cause. Binary/database compatibility is important, API can be improved with breaking changes.

2022-05-29 21:47 UTC, drieseng commented
@lahma jobContext.JobDetail.JobType.ToString() will always return **Quartz.Impl.JobType**. I don't think that's what was intended. This can be fixed of course, but I won't necessarily match what was previous returned (by **Type.ToString()**).

It's just an example of where these changes are breaking, but not in a way that is immediately clear. 

I have no problem at all with breaking API changes. It's just that here the breaking changes are perhaps a little too subtle.
It's of course up to you to decide how to proceed with these changes. Maybe I'm being too cautious here.

2022-05-29 21:57 UTC, lahma commented
Current support contracts allow quite a lot of breaking changes 😉