use property names instead of reflection
quartznet/quartznet pull request #1613
Opened 2022-05-22 12:49 UTC by tonyqus

2022-05-22 17:44 UTC, lahma requested changes
Can you also delete the now obsolete `SchedulerDetailsSetter`? In the future, it would nice if you could create a separate branch for each PR in your fork - this allows me to to rebase etc the PR if needed - I usually cannot push to anyone's main branch.

**EDIT** I also edited the description with "fixes #1407" , this single line comment makes sure we have PR and issue in sync. After merge the issue gets closed.

2022-05-22 22:27 UTC, tonyqus commented
I've deleted `SchedulerDetailsSetter`. 

Ok. I'll use branch instead of main in the future.

2022-05-23 05:22 UTC, lahma approved these changes

2022-05-23 05:23 UTC, merged

2022-05-23 05:23 UTC, lahma commented
Thank you!